update: validation
koki-takishita/home-care-navi-api pull request #30
Opened 2022-05-13 02:03 UTC by suwonkun

## 例

[link](https://dev.classmethod.jp/articles/pull-request-template/)

## チケットへのリンク

* https://example.com

## やったこと

userモデルに二重にかかっていたバリデーションを修正

## やらないこと

なし

## できるようになること（ユーザ目線）

なし

## できなくなること（ユーザ目線）

なし

## 動作確認

なし

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2022-05-13 02:04 UTC, tmhr0 approved these changes
確認OK。

2022-05-13 02:23 UTC, koki-takishita commented
OK

2022-05-13 02:23 UTC, koki-takishita approved these changes

2022-05-16 02:16 UTC, watasho358 requested changes
バリデーションが二重に出ます。
![image](https://user-images.githubusercontent.com/34031637/168508752-0c27071b-710c-40e1-8710-c81eca7333aa.png)

2022-05-16 02:32 UTC, suwonkun commented
emailのユニーク制約が二重にかかっていたため、ユニークを電話番号に修正
修正
https://gyazo.com/0447b97967444970ddb98ed61839fc14

2022-05-16 02:33 UTC, watasho358 approved these changes
OKです

2022-05-16 02:33 UTC, merged