postmanからログイン・ログアウト処理ができる
koki-takishita/home-care-navi-api pull request #31
Opened 2022-05-16 03:13 UTC by koki-takishita

## やったこと
1. `app/mode/user.rb`内、deviseの`trackable`の無効化 
```ruby
# app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable,
         :validatable, :registerable, :omniauthable

  # 上記のdeveseオプションのtrackable削除
  :trackable

  include DeviseTokenAuth::Concerns::User
end
```
[Qiita::削除した背景](https://qiita.com/terufumi1122/items/d5530bc87689d886dee8)
[stackOverFllow::より詳しい説明や理由](https://stackoverflow.com/questions/33008187/devise-error-undefined-method-current-sign-in-ip)
2. middleware追加 セッションを維持してくれない
```ruby
# config/application.rb
module Api
  class Application < Rails::Application
    config.load_defaults 7.0
    config.i18n.default_locale = :ja
    config.time_zone = 'Tokyo'
    config.active_record.default_timezone = :local
    config.api_only = true
    # 追加
    config.middleware.use ActionDispatch::Session::CookieStore
  end
end
```
## やらないこと

画面からはできない・まだPOSTMANのみ

## できるようになること（ユーザ目線）

APIを直接叩けばログイン処理ができる

## 動作確認
- 下記手順動画
https://www.loom.com/share/f4a1eb32b51841499ad85c9c4d2710ba
1. パラメータセットしてログインする
2. 前回のheader情報をリクエストheaderにセットする(動画参照)
3. ログアウトをリクエストする

## 使用するパラメータなど
- 前提
**本登録を済ませたカスタマーが存在すること**
- セットするパラメーター (人によって変わる)
```ruby
email: foobar111@example.com
password: password
```
- ログインAPI
```ruby
http://localhost:3000/api/users/sign_in
```
- ログアウトAPI
```ruby
http://localhost:3000/api/users/sign_out
```

2022-05-16 08:00 UTC, watasho358 requested changes
ログアウトできません。ユーザーは認証済みです。動画の通りclient、uid、access-tokenをコピーして貼り付けました
![image](https://user-images.githubusercontent.com/34031637/168546319-4d77c4b3-c7c1-47b5-8f06-16d0fe5c979e.png)

2022-05-16 08:02 UTC, koki-takishita commented
> ログアウトできません。ユーザーは認証済みです。動画の通りclient、uid、access-tokenをコピーして貼り付けました ![image](https://user-images.githubusercontent.com/34031637/168546319-4d77c4b3-c7c1-47b5-8f06-16d0fe5c979e.png)
`config/application.rb`みせてください

2022-05-16 08:03 UTC, watasho358 commented
```
require_relative "boot"

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_mailbox/engine"
require "action_text/engine"
require "action_view/railtie"
require "action_cable/engine"
# require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Api
  class Application < Rails::Application
    config.load_defaults 7.0
    config.i18n.default_locale = :ja
    config.time_zone = 'Tokyo'
    config.active_record.default_timezone = :local
    config.api_only = true
    config.middleware.use ActionDispatch::Session::CookieStore
  end
end
```

2022-05-16 08:57 UTC, suwonkun approved these changes
OK

2022-05-16 08:57 UTC, watasho358 approved these changes
＼(^o^)／

2022-05-17 01:41 UTC, tmhr0 approved these changes
確認OK

2022-05-17 01:41 UTC, merged