Apiのみでdetailデータを登録
koki-takishita/home-care-navi-api pull request #74
Opened 2022-06-23 02:23 UTC by tmhr0

## 例

[link](https://dev.classmethod.jp/articles/pull-request-template/)

## チケットへのリンク

* https://example.com

## やったこと

* API側でのデータ登録確認

## やらないこと

* 同じOffice_idで複数 Office_Detailのデータが登録できてしまう仕様。

## できるようになること（ユーザ目線）

なし

## できなくなること（ユーザ目線）
なし

## 動作確認

- フロントでケアマネとしてログインして、uid・access-token・clientを確認
http://localhost:8000/specialists/login
```ruby
specialist3@example.com
password
```

- コンテナ入る
```ruby
docker-compose exec web bash
```
- seed実行
```ruby
rails db:seed
```

コンソール上でOfficeデータの一覧を確認。
```ruby
rails c
```
```ruby
Office.all
```

存在するOffice_idを使って、Postmanで直接データを送る。
```ruby
localhost:3000/api/specialists/offices/96/office_details
```
以下を設定
```
Header↓
uid　
access-token　
client　
```
```
Body
from-data↓
office_id　94,
detail　テスト
service_type　テスト成功
open_date　2022-06-22
rooms　30
requirement　入居時の要件
facility　共用設備
management　事業主体
link　https://railsdoc.com/rails_base
```
コンソール上で登録データを確認。
```ruby
rails c
```
```ruby
OfficeDetail.all
```

[手順確認動画](https://www.loom.com/share/dbf430ff46424f45a802c8623ee2e4b6)

### 確認書類
[API 一覧](https://docs.google.com/spreadsheets/d/1sJ_ZjXjCdBJkpl0gbS_HX3wDeZhihUoqddtIrHCPFnY/edit#gid=0)

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2022-06-23 03:38 UTC, watasho358 submitted a review, later dismissed
動作確認OK

2022-06-23 03:51 UTC, suwonkun submitted a review, later dismissed
確認OKです

2022-06-23 04:35 UTC, tmhr0 commented on app/controllers/api/specialists/office_details_controller.rb
> +    office_details = OfficeDetail.new(office_details_params)
@koki-takishita 
> もし無理やりやろうとするなら下記の対応が必要です これは櫛田さんの選択次第なのでなんとも言えません
> 
> 1. オフィスが作成されたことをフロント側で検知
> 2. 検知したら、detailの作成のリクエストをapiへ投げる
>    1、2ができるならこのapiでも一応はできそうです

自分もこの処理で調べてはいましたが、実装させるまでに使用する技術がまだ具体化できてません。
同時登録パターンでの、一部参考中の記事：
https://qiita.com/saitaman_zarathustra/items/dec7e1c2bb64ed57ccc4

事業所登録ページ⇨事業所詳細ページ　と遷移させながら登録させることも考えましたが、
詳細テーブルにもimagecommentテーブルとの同時登録があるので、これだとページが合計３枚に増えることになります。

2022-06-23 04:40 UTC, tmhr0 commented on app/controllers/api/specialists/office_details_controller.rb
> +    office_details = OfficeDetail.new(office_details_params)
detailテーブル自体は必要なのでしょうか。
office内にdetail系データやimege-comment系データを全ておさめた方が良いのかもと考えてもいます。

2022-06-23 04:41 UTC, koki-takishita commented on app/controllers/api/specialists/office_details_controller.rb
> +    office_details = OfficeDetail.new(office_details_params)
ひつようですよ
データを格納する必要があるので、officeのcreateコントローラーの中でoffice_detailを参照すればできる
office_detailコントローラー内でしかoffice_detailにアクセスできないということはないです。

2022-06-23 04:42 UTC, koki-takishita commented on app/controllers/api/specialists/office_details_controller.rb
> +    office_details = OfficeDetail.new(office_details_params)
というかもう作ってあるのでoffice_detailテーブル自体は作ってあるので作る必要はありませんが

2022-06-23 04:46 UTC, koki-takishita commented on app/controllers/api/specialists/office_details_controller.rb
> +    office_details = OfficeDetail.new(office_details_params)
分ける意味について聞いていますかね？
detailとofficeを統合してしまうと、属性の数がすごいことになりますよね？
コードのみやすさや関心事ごとにごとに分ける意味でもテーブルを分割しています。
オフィスの基本情報と詳細情報に分けているという意味です。

櫛田さんの基本情報と詳細な情報は別のカテゴリーとして扱ってますよね？そういう意味です。
基本情報: 年齢：生年月日：人間など
詳細情報: 趣味:休日の過ごし方:仕事

2022-06-30 07:34 UTC, koki-takishita reviewed
コメント確認お願いします。

2022-06-30 07:34 UTC, koki-takishita commented on app/controllers/api/specialists/offices_controller.rb
> +    test = true
test以外で

2022-06-30 07:34 UTC, koki-takishita commented on app/models/office_detail.rb
> +  belongs_to :office, foreign_key: 'office_id',
foreign_key: 'office_id'
これ指定しているのはなぜ？
いらなくない？

2022-06-30 07:34 UTC, koki-takishita commented on app/models/office.rb
> +  accepts_nested_attributes_for :office_detail
これ何している？

2022-06-30 07:39 UTC, tmhr0 commented on app/models/office_detail.rb
> +  belongs_to :office, foreign_key: 'office_id',
指定が必要と思って記述はしましたが、belongs_to :と表現が被ってたりしますか？

2022-06-30 07:44 UTC, tmhr0 commented on app/models/office.rb
> +  accepts_nested_attributes_for :office_detail
親子テーブルの登録の際に使われる構文とのことで記述しました。
親：officeデータの登録をするとき、子：office_detailデータも登録するよう指示するイメージ。

2022-06-30 07:46 UTC, koki-takishita commented on app/models/office.rb
> +  accepts_nested_attributes_for :office_detail
これはないと動かないのですか？

2022-06-30 07:46 UTC, koki-takishita commented on app/models/office_detail.rb
> +  belongs_to :office, foreign_key: 'office_id',
belongs_to :office, dependent: :destroy これだけでいいと思いますよ

2022-06-30 07:48 UTC, watasho358 commented
送信ができません。
![image](https://user-images.githubusercontent.com/34031637/176622494-24a86c82-2758-445a-961c-e9393abf5df3.png)

2022-06-30 07:52 UTC, koki-takishita commented on app/controllers/api/specialists/offices_controller.rb
> +    test = true
apiはこれで完結ではないのですか？

2022-06-30 07:52 UTC, koki-takishita commented on app/controllers/api/specialists/offices_controller.rb
> +    test = true
次回まで？
apiはこれで完結ではなくてまだ実装することある？

2022-07-05 07:13 UTC, watasho358 requested changes
```ruby
     def detail_params
       params.require(:office_detail_attribute)
       .permit(:detail, :service_type, :open_data, :rooms, :requirement, :facility, :management, :link)
     end
```

タイポ　:open_data → :open_date

2022-07-05 07:24 UTC, koki-takishita commented
進捗どうですかね？
これ取り込むと、オフィスの作成と共通になるためオフィスのみ画面で作成はできる状態が好ましいです。
※ 一時的にオフィスが作成できなくなるのを許容するならいいですが、許容しないほうが良いでしょう
なのでフロントのテストをすべてパスするかどうか確認お願いします。
パスしてないようであれば、パスするまでdraftでお願いします。

2022-07-05 07:33 UTC, tmhr0 commented
@koki-takishita 
現状は、こちらを取り込むのは危険だと思いますので、Draft化しておきます。
FRONTとのAPI連携が出来たら、またこちらも確認してもらう形にします。

2022-08-02 11:37 UTC, closed without merging